# Generated by Django 4.0.4 on 2022-04-14 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_materia', models.CharField(max_length=200)),
                ('materia', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('data_materia', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
