# Generated by Django 4.0.4 on 2022-04-15 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtores', '0001_initial'),
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='pessoa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='produtores.produtores'),
            preserve_default=False,
        ),
    ]
