# Generated by Django 4.0.4 on 2022-04-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_materia_resumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='resumo',
            field=models.TextField(max_length=600),
        ),
    ]
