# Generated by Django 4.0.4 on 2022-04-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_materia_resumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='resumo',
            field=models.CharField(max_length=200),
        ),
    ]
