# Generated by Django 4.0.4 on 2022-04-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_materia_resumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='resumo',
        ),
    ]
