# Generated by Django 4.0.4 on 2022-04-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_remove_materia_resumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='resumo',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
