# Generated by Django 4.0.4 on 2022-04-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_materia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
